controller_list:
  - name: fake_leftArm_controller
    joints:
      - l_shoulder_z
      - l_shoulder_y
      - l_arm_x
      - l_elbow_y
      - l_wrist_z
      - l_wrist_x
  - name: fake_rightArm_controller
    joints:
      - r_shoulder_z
      - r_shoulder_y
      - r_arm_x
      - r_elbow_y
      - r_wrist_z
      - r_wrist_x
  - name: fake_leftLeg_controller
    joints:
      - l_hip_z
      - l_hip_x
      - l_hip_y
      - l_knee_y
      - l_ankle_y
      - l_ankle_x
  - name: fake_rightLeg_controller
    joints:
      - r_hip_z
      - r_hip_x
      - r_hip_y
      - r_knee_y
      - r_ankle_y
      - r_ankle_x